# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6901c9c2fee24c79fa44c7a26cb8b16895aa690e1fda1e9aea754d675f1d78aacf2cf1fc0c2ce60bba2cf0b4e4babdd6ab005ef00fe8bf628bf3011ea290a0

test:
  secret_key_base: cc05de5b1b9a04b4c2854895867deedd0ff51e708c598addab67eaa5a0ab4dccb5ad37f49181b73e5d7e3e9422a5c9af5d70f345d7539d0bdc780313affbfbfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
